### ISSUE TITLE
Possibility of pass-through Point2, Point3 types?

### ISSUE THREAD

**Issue by etjones** [dov/npeuclid#1]
It looks like a design goal for npeuclid was to remove the Point2 & Point3 classes, since they function mathematically [largely] the same as Vec[2|3]s.  However, for any existing codebase that makes use of Point3s, it seems like that might making transitioning extra difficult. At the very least, something like: 

```python
class Point3(Vec3):
    pass
```

would allow an easier transition. Open to any of that?

**Comment by dov** [comment]
Thanks for the suggestion, but I'd rather not adher to closely to the pyeuclid, but would rather retain the freedom of finding my own path. Let's say that I drew a lot of inspiration and copied a lot of code from euclid, but I don't want to constrain myself to being API compatible.

For your own application you can always monkey patch to get the above functionality. But just the inline vs mutability of the transformations is enough incompatibility to hit you in other places.

But feel free to contribute suggestions and patches!

**Comment by etjones** [comment]
Nicely said. Best of luck!
